# Generated by Django 4.2.2 on 2024-12-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_pendingrequest_assistant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='status',
            field=models.CharField(blank=True, default='available', max_length=255, null=True),
        ),
    ]
